#!/bin/python
import os
import sys
import time
import serial
from inputs import get_gamepad

#navázání komunikace (když se spustí conn)
conn = serial.Serial("/dev/ttyACM0", 9600, timeout=1)

while True:
    if len(sys.argv) > 1: #bez arg se argv == 1, tj. jméno souboru
        for arg in sys.argv[1:]: #['jmeno_souboru', 'arg1', ...]
            if os.path.isfile(arg): #souborové zadání (provede a ukončí)
                with open(arg, "r", encoding="utf-8") as soubor:
                    for line in soubor:
                        #conn.write((line.strip() + "\n").encode()) #strip() odebere přebytečné \n
                        conn.write((line).encode())
                    INPUT = "exit"
            elif arg == "gamepad": #gamepad zadání: M17 a z gamepad
                S = 0
                conn.write(("M17\n").encode())
                while True:
                    for INPUT in get_gamepad():
                        if INPUT.ev_type == "Key" and INPUT.code == "BTN_NORTH" and INPUT.state == 0:
                            conn.close()
                            if conn.is_open:
                                print("je to pořád připojený!!!!!.")
                            else:
                                sys.exit()
                        if INPUT.ev_type == "Absolute" and INPUT.code == "ABS_HAT0X":
                            if INPUT.state != 0:
                                ROTACE = INPUT.state
                                START_TIME = time.time()
                            else:
                                PRESS_TIME = int(time.time() - START_TIME)
                                if ROTACE == 1:
                                    S += int(PRESS_TIME*20)
                                if ROTACE == -1:
                                    S -= int(PRESS_TIME*20)
                                INPUT = f"G1 F500 X{S}"
                                print(INPUT)
                                conn.write((INPUT + "\n").encode())
                                OUTPUT = ""
                                while True:
                                    OUTPUT += conn.read(conn.in_waiting).decode()
                                    if OUTPUT.endswith("ok\n"):
                                        break
                                print(OUTPUT, end="") #end="" smaže zbytečné \n
            else:
                conn.write((arg + "\n").encode()) #argumentové zadání (provede a ukončí)
                INPUT = "exit"
    else:
        INPUT = input() #manuální zadání

    if INPUT == "exit":
        conn.close() #může selhat!!!
        #sanity check
        if conn.is_open:
            print("je to pořád připojený!!!!!.")
        else:
            break

    if INPUT == "":
        continue #přeskočí to kód dole

    conn.write((INPUT + "\n").encode())

    OUTPUT = ""
    while True:
        OUTPUT += conn.read(conn.in_waiting).decode()
        if OUTPUT.endswith("ok\n"):
            break

    print(OUTPUT, end="") #end="" smaže zbytečné \n
